{
 "title": "NodeExporter",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=\"nodeexporter:9100\", mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Load Average 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{instance=\"nodeexporter:9100\"}",
     "legendFormat": "{{instance}} - Load Average 1m"
    },
    {
     "expr": "node_load5{instance=\"nodeexporter:9100\"}",
     "legendFormat": "{{instance}} - Load Average 5m"
    },
    {
     "expr": "node_load15{instance=\"nodeexporter:9100\"}",
     "legendFormat": "{{instance}} - Load Average 15m"
    }
   ]
  },
  {
   "title": "Free & Available memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"nodeexporter:9100\"}",
     "legendFormat": "Free memory"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\"}",
     "legendFormat": "Available memory"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!~\"tmpfs|devtmpfs|overlay|squashfs|proc|sysfs\"}"
    }
   ]
  }
 ]
}